services:
  gophish:
    build:
      context: ./gophish
      dockerfile: Dockerfile.gophish
    image: gophish
    container_name: gophish
    restart: unless-stopped

    ports:
      - "3333:3333"
      - "8080:8080"
      
    volumes:
      - gophish-db:/db

    networks:
      - phisher-net

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped

    ports:
      - "80:80"

    networks:
      - phisher-net

networks:
  phisher-net:
    driver: bridge

volumes:
  gophish-db:
